services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000" # GraphQL
      - "8001:8001" # Admin
      - "8020:8020" # Indexer
      - "8030:8030" # Metrics
    depends_on:
      - postgres
      - ipfs
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      ipfs: "ipfs:5001"
      ethereum: "anvil:http://host.docker.internal:8545"
      GRAPH_LOG: info

  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
